### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by ghost** [fellows-in-innovation/website#3]
@rossdakin Hi Ross The current CNAME points to fellowsininnovation.us  but it also points to https://fellows-in-innovation.pif.gov/ I don't if its correct as both are live and with the same update.Thank you. 

Thank you for the encouragement which make me work hard I  am working Margaret and Lindsay  with their survey app. I have some tech questions can I please email.Sorry for the trouble.

**Comment by rossdakin** [comment]
Hi Neil — thanks for checking on this! You're correct: the site is currently hosted in two places:
- https://fellows-in-innovation.pif.gov is via cloud.gov, which is nice because it's a .gov, but somewhat undesirable in that it's then implicitly associated with PIF (whereas the spirit is to be inclusive of all fellowships in the Executive branch).
- https://fellowsininnovation.us is via GitHub Pages via CloudFlare, which is nice in that it's fellowship agnostic and a great (free) way to host such a simple static website; while it loses the qualities of the .gov TLD, it is still indicative of the U.S. Government by being a .us TLD (though I'm not sure if that's sufficient to imply government; I recently saw something about *.fed.us being the standard under .us). Because this is an informal gathering organized outside the scope of our official capacities and because this website is not directed toward the public and does not claim to be an official website of the U.S. Government, I don't imagine the lack of a .gov TLD is an issue (though I'm sure that's a debatable point).

**Comment by ghost** [comment]
@rossdakin Thank you Ross! I have some tech queries
